### PR TITLE
Itsnoteasy patch 1

### PR DESCRIPTION
**Pull request by itsnoteasy**
I rerouted the pcb to avoid using trace vias which can go high resistance. this should lower manufacturing cost and increase reliability. no components were moved, but r4 and boot switch were inverted. all existing cases will work as will the existing unmodified firmware.

### CODE REVIEW

**Comment by hsgw** [comment]
Thanks for your contribute.
I will look into this.

**Comment by hsgw** [comment]
Did you work on kicad nightly build?
I can't open this on 5.1.5.

**Comment by itsnoteasy** [comment]
that's correct, i used the kicad nightly development build. i had difficulty installing the stable version on my linux system.

**Comment by hsgw** [comment]
This is just my opinion.   
I think we shouldn't use nightly build, because it is not standard.
   
I want to keep opening and modifying easy as much as possible.

BTW, thank you so much for your contribute.

**Comment by itsnoteasy** [comment]
I understand. Do you want me to redo the contribution in kicad standard or is there no need?

**Comment by hsgw** [comment]
That is largely welcomed.   

I think it will take some time to confirm that it works correctly.
But I will help.

Thanks.

**Comment by mengstr** [comment]
Hmmm... 

> "I rerouted the pcb to avoid using trace vias which can go high resistance. this should lower manufacturing cost and increase reliability."

That's a very interesting claim.  I'd be really interested in seeing some reports that backs that up.  

I mean - considering the average cellphone or PC motherboard literally have thousands upon thousands of them (and also mostly in the form of microvias) phones and PCs should fail and go dead all over the place.  And the PCB manufacturing costs is the same for 25 or 800 vias unless you have them made in huge volumes with negotiated prices.

But on the other hand it's fun to route PCBs - I do it every now and then just for the meditative and relaxing feeling while routing, ripping up, improving and at the same time keep it electrically sound and well as aesthetically nice.  So why not?  ^__^

**Comment by itsnoteasy** [comment]
ok, i have uploaded the redone pcb files on kicad standard to itsnoteasy-patch-1 on my fork. do i need to do another pull request or is it sufficient?

**Pull request closed without merging**
