### PR TITLE
Add BOM. doesn't include switches.

### PR DESCRIPTION
**Pull request by themoonisacheese**
BOM has been generated through digi-key.
rubber pads are a bit big.

### CODE REVIEW

**Comment by hsgw** [comment]
Thanks!

**Comment by hsgw** [comment]
Sorry.   
I was overlooking resistor issues.   
And I checked simply, the USB connector is not correct.   
So this commit is reverted.

**Comment by hsgw** [comment]
USB connector is XM7D-0512 or equivalent.   
I will add this to build guide.

**Comment by themoonisacheese** [comment]
I mounted it without problems. Although it doesn't have the "right" mounting hardware, it fits.
A more serious problem is that the resistors I chose are too big.
I will also modify the quantities so that they're appropriate. For example, buying 100 diodes was 3 cents cheaper for me than buying 48 of them, but that may not be the case for everyone.

**Comment by hsgw** [comment]
> I mounted it without problems.

Sounds good 💯    
In Japanese store, this 4 legs type USB miniB connector is cheap. But mouser or digikey is not. Thank you for the information.   

> buying 100 diodes

Typical story :)   
But "official" BOM contains only required quantity, I think.

Anyway, I am meaning to publish BOM after I publish Rev.1 pcb.

**Comment by themoonisacheese** [comment]
Sounds good

**Pull request merged**
